name: Auto Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.VM_SSH_KEY }}
          script: |
            # Clone or update the repository
            if [ -d "~/spatial-frontendv2" ]; then
              cd ~/spatial-frontendv2
              git pull origin main
            else
              git clone https://github.com/mobile-cloud-computing/spartial-frontendv2.git ~/spatial-frontendv2
              cd ~/spatial-frontendv2
            fi

            # Install Docker and Docker Compose if not present
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | grep -Po '"tag_name": "\K.*?(?=")')/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Deploy using Docker Compose
            docker-compose down
            docker-compose up -d --build
