name: Auto Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent with private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      # Step 3: Deploy to VM
      - name: Deploy to VM
        env:
          VM_IP: ${{ secrets.VM_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$VM_IP "
            # Navigate to the app directory on the VM
            cd ~/spartial-frontendv2 || exit 1

            # Pull the latest changes
            git pull origin master

            # If using Docker, rebuild and restart the container
            sudo docker compose down
            sudo docker compose up -d --build

            # Or, if not using Docker, build and restart the application
            sudo npm install
            pm2 restart app_name
          "
