name: Auto Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent with private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      # Step 3: Deploy to VM
      - name: Deploy to VM
        env:
          VM_IP: ${{ secrets.VM_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$VM_IP << 'EOF'
            # Navigate to the app directory on the VM
            cd ~/spartial-frontendv2 || exit 1

            # Pull the latest changes
            git pull origin main

            # Ensure Docker Compose is installed
            if ! command -v docker-compose &> /dev/null; then
              sudo curl -L "https://github.com/docker/compose/releases/download/v2.1.1/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
              sudo chmod +x /usr/local/bin/docker-compose
            fi

            # Ensure Node.js and npm are installed
            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              sudo npm install -g pm2
            fi

            # Install dependencies
            sudo npm install

            # If using Docker, rebuild and restart the container
            sudo docker-compose down
            sudo docker-compose up -d --build

            # If not using Docker, start the application with PM2
            if pm2 describe spartial-app > /dev/null; then
              pm2 restart spartial-app --update-env
            else
              pm2 start npm --name spartial-app -- run start
            fi
          EOF
