name: Auto Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VM via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.VM_IP }}
          username: ${{ secrets.SSH_USERNAME }}
          key: "${{ secrets.VM_SSH_KEY }}"
          # If using base64 encoding:
          # key: "${{ secrets.VM_SSH_KEY_BASE64 }}"
          # key_is_b64: true
          script: |
            # Navigate to the app directory or clone if it doesn't exist
            if [ -d ~/spatial-frontendv2 ]; then
              cd ~/spatial-frontendv2
              git pull origin main
            else
              git clone https://github.com/mobile-cloud-computing/spartial-frontendv2.git ~/spatial-frontendv2
              cd ~/spatial-frontendv2
            fi

            # Ensure Node.js (version 18) and npm are installed
            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi

            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi

            # Kill any process running on port 3000
            if lsof -i:3000; then
              sudo kill -9 $(lsof -t -i:3000) || true
            fi

            # Stop and remove any existing Docker container named 'spatial-app'
            if [ "$(docker ps -q -f name=spatial-app)" ]; then
              docker stop spatial-app
              docker rm spatial-app
            fi

            # Remove any Docker containers using port 3000
            if [ "$(docker ps -q -f publish=3000)" ]; then
              docker stop $(docker ps -q -f publish=3000)
              docker rm $(docker ps -q -f publish=3000)
            fi

            # Build Docker image
            docker build -t spatial-frontendv2 .

            # Run the Docker container
            docker run -d --name spatial-app -p 3000:3000 -e DANGEROUSLY_DISABLE_HOST_CHECK=true spatial-frontendv2
