name: Auto Deploy to VM

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout Repository
        uses: actions/checkout@v2

      # Step 2: Set up SSH agent with private key
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.VM_SSH_KEY }}

      - name: Deploy to VM
        env:
          VM_IP: ${{ secrets.VM_IP }}
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
        run: |
          ssh -o StrictHostKeyChecking=no $SSH_USERNAME@$VM_IP << 'EOF'
            # Navigate to the app directory on the VM
            cd ~/spartial-frontendv2 || exit 1
          
            # Mark the directory as safe for Git
            git config --global --add safe.directory /home/***/spartial-frontendv2
          
            # Pull the latest changes
            git pull origin main
          
            # Ensure Node.js (version 18) and npm are installed
            if ! command -v npm &> /dev/null; then
              curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
              sudo apt-get install -y nodejs
            fi
          
            # Ensure Docker is installed
            if ! command -v docker &> /dev/null; then
              sudo apt-get update
              sudo apt-get install -y docker.io
              sudo systemctl start docker
              sudo systemctl enable docker
            fi
          
            # Install dependencies
            sudo npm install
          
            # Fix any npm vulnerabilities
            sudo npm audit fix || sudo npm audit fix --force
          
            # Stop the existing Docker container (if running)
            if [ "$(docker ps -q -f name=spartial-app)" ]; then
              sudo docker stop spartial-app
              sudo docker rm spartial-app
            fi
          
            # Run the Docker container
            sudo docker run -d \
              --name spartial-app \
              -p 3000:3000 \
              -e DANGEROUSLY_DISABLE_HOST_CHECK=true \
              -v ~/spartial-frontendv2:/app \
              -w /app \
              node:18 \
              sh -c "npm install && npm run start"
          EOF
